Repository kingwrcy/moments, pull requests merged in 2025-02, with the labels that each got.

#279 修改后端获取前端域名的方式
  backend/handler/comment.go
  backend/handler/rss.go
  front/components/CommentBox.vue
  front/layouts/default.vue
  front/nuxt.config.ts
Labels: feature

#280 优化图片展示和上传
  backend/db/memo.go
  backend/handler/file.go
  backend/handler/memo.go
  backend/handler/rss.go
  backend/vo/memo_vo.go
  front/components/Memo.vue
  front/components/MemoEdit.vue
  front/components/UploadImage.vue
  front/components/UploadImagePreview.vue
  front/pages/sys/settings.vue
Labels: feature

#281 只在启用邮件通知时显示相关配置项
  front/pages/sys/settings.vue
Labels: feature

#282 整理文档格式: README.md, docker-compose.yml
  README.md
  docker-compose.yml
Labels: doc

#284 格式化 README.md，更新贡献者
  .all-contributorsrc
  README.md
Labels: doc

#291 自动备份数据库
  backend/backup.go
  backend/main.go
Labels: feature

#292 检查是否备份数据库文件增加 commitId 条件
  backend/backup.go
Labels: bugfix

#293 gorm实例复用导致sql污染
  backend/handler/memo.go
Labels: bugfix
